version: 2.0

jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      # Run python script
      - run: pip3 install PyGithub --user
      - run: pip3 install wordcloud --user
      - run: pip3 install matplotlib --user
      - run: python3 main.py
      - run: git version
      - run: git status
      - run: git config --global user.email "1639301503@qq.com"
      - run: git config --global user.name "jwenjian"
      - run: git add .
      - run: git commit -m "Update From Circle CI"
      - run: git push https://$GITHUB_LOGIN:$GITHUB_TOKEN@github.com/$GITHUB_LOGIN/ghiblog.git
      - run: echo 'done'

workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master

    jobs:
      - build
